-- DROP TABLE franquicias;

CREATE TABLE franquicias (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar NOT NULL,
	CONSTRAINT franquicias_pkey PRIMARY KEY (id)
);

-- DROP TABLE sucursales;

CREATE TABLE sucursales (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar NOT NULL,
	id_franquicia int8 NOT NULL,
	CONSTRAINT sucursales_pkey PRIMARY KEY (id)
);


-- sucursales foreign keys

ALTER TABLE sucursales ADD CONSTRAINT fk_franquicia FOREIGN KEY (id_franquicia) REFERENCES franquicias(id) ON DELETE CASCADE;

-- DROP TABLE productos;

CREATE TABLE productos (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar NOT NULL,
	id_sucursal int8 NOT NULL,
	stock int8 NOT NULL,
	CONSTRAINT productos_pkey PRIMARY KEY (id)
);


-- productos foreign keys

ALTER TABLE productos ADD CONSTRAINT fk_surcusales FOREIGN KEY (id_sucursal) REFERENCES sucursales(id) ON DELETE CASCADE;