server:
  port: ${PORT:80}
spring:
  application:
    name: franquicias
  datasource:
    url: ${URL_DB}
    username: ${USER_DB}
    password: ${PASS_DB}
    #url: ${URL_DB:jdbc:mysql://localhost:3306/nequi}
    #username: ${USER_DB}
    #password: ${PASS_DB}
    #driver-class-name: "com.mysql.cj.jdbc.Driver"
